### ISSUE TITLE
How to generate position images of each trajectory at testing stage

### ISSUE THREAD

**Issue by yingchengyang** [facebookresearch/habitat-lab#1013]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: master

Habitat-Sim: master

## ❓ Questions and Help

Thanks a lot for designing such an excellent codebase for Embodied AI! I have some questions about how to generate position images, i.e., a map with the route of the agent like Fig. 4 and Fig. 12 in [1], in the videos when testing in the pointnav task. What parameters can I set to achieve this goal?

Thank you!

[1] Savva M, Kadian A, Maksymets O, et al. Habitat: A platform for embodied ai research[C]//Proceedings of the IEEE/CVF International Conference on Computer Vision. 2019: 9339-9347.

**Comment by dhruvbatra** [comment]
Please go through the Hab-Sim basics for Navigation tutorial here: https://aihabitat.org/tutorial/2020/
