### ISSUE TITLE
Non-abstract Parallel Gripper 

### ISSUE THREAD

**Issue by jzhzhang** [facebookresearch/habitat-lab#1033]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v2.x.x or master?

Habitat-Sim: v2.x.x or master?

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest release versions of [Habitat-Lab](https://github.com/facebookresearch/habitat-lab/releases) and [Habitat-Sim](https://github.com/facebookresearch/habitat-sim/releases)? Your question may already be addressed in the latest versions. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Master branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-lab/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help

I noticed that your paper ```Habitat 2.0: Training Home Assistants to Rearrange their Habitat ```  and openreview ```https://openreview.net/forum?id=DPHsCQ8OpA``` mentioned that ```Habitat 2.0 supports rigid-body mechanics of grasping``` you can ```remove the abstracted grasping and ran experiments for the pick task with full grasping``` .

However, I only find two types of grip control ```MagicGraspAction``` and ```SuctionGraspAction```. Can you give me some advice on how to use full grasping of the parallel gripper?

**Comment by aclegg3** [comment]
@jzhzhang 

Habitat supports articulated dynamics. You can use the motor controllers or other parts of the  ArticulatedObject API to setup an experiment where the gripper is used to manipulate objects. We are unlikely to add this in the near future.
