### ISSUE TITLE
Cannot test PointNav example, with the error 'omegaconf.errors.ConfigAttributeError: ListConfig does not support attribute access'

### ISSUE THREAD

**Issue by Yuchen-Song** [facebookresearch/habitat-lab#1073]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.2.3 (stable)

Habitat-Sim: v0.2.2 (stable)

## Steps to Reproduce

1. Install habitat-sim (headless & bullet) through anaconda, as stated in guidelines `conda install habitat-sim withbullet headless -c conda-forge -c aihabitat`
2. pip install habitat-lab stable version `pip install -e habitat-lab`
3. Test the pointNav task `python examples/example_pointnav.py`

## Expected behavior

Error messages are: 

> Traceback (most recent call last):
>   File "/home/[MyUserName]/habitat-lab/examples/example_pointnav.py", line 30, in <module>
>     example()
>   File "/home/[MyUserName]/habitat-lab/examples/example_pointnav.py", line 19, in example
>     observations = env.reset()  # noqa: F841
>   File "/home/[MyUserName]/habitat-lab/habitat-lab/habitat/core/env.py", line 260, in reset
>     self.reconfigure(self._config)
>   File "/home/[MyUserName]/habitat-lab/habitat-lab/habitat/core/env.py", line 345, in reconfigure
>     self._sim.reconfigure(self._config.simulator)
>   File "/home/[MyUserName]/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 451, in reconfigure
>     self._update_agents_state()
>   File "/home/[MyUserName]/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 395, in _update_agents_state
>     agent_id,
>   File "/home/[MyUserName]/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 593, in set_agent_state
>     agent.set_state(new_state, reset_sensors)
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim/agent/agent.py", line 255, in set_state
>     self.body.object.rotation = quat_to_magnum(state.rotation)
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim/utils/common.py", line 49, in quat_to_magnum
>     return mn.Quaternion(quat.imag, quat.real)
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/omegaconf/listconfig.py", line 185, in __getattr__
>     "ListConfig does not support attribute access"
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/omegaconf/base.py", line 237, in _format_and_raise
>     type_override=type_override,
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
>     _raise(ex, cause)
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/omegaconf/_utils.py", line 797, in _raise
>     raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
> omegaconf.errors.ConfigAttributeError: ListConfig does not support attribute access
>     full_key: habitat.simulator.agents.main_agent.start_rotation[imag]
>     reference_type=List[float]
>     object_type=list

## Additional context

The whole output in the console: 

> /home/[MyUserName]/anaconda3/envs/habitat/bin/python /home/[MyUserName]/habitat-lab/examples/example_pointnav.py 
> pybullet build time: Sep 22 2020 00:55:20
> 2023-01-10 16:04:12,463 Initializing dataset PointNav-v1
> 2023-01-10 16:04:12,706 initializing sim Sim-v0
> [16:04:12:711116]:[Metadata] AttributesManagerBase.h(380)::createFromJsonOrDefaultInternal : <Dataset>: Proposing JSON name : default.scene_dataset_config.json from original name : default| This file does not exist.
> [16:04:12:711208]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (capsule3DSolid:capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false) created and registered.
> [16:04:12:711233]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (capsule3DWireframe:capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1) created and registered.
> [16:04:12:711251]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (coneSolid:coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true) created and registered.
> [16:04:12:711265]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (coneWireframe:coneWireframe_segments_32_halfLen_1.25) created and registered.
> [16:04:12:711278]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cubeSolid:cubeSolid) created and registered.
> [16:04:12:711295]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cubeWireframe:cubeWireframe) created and registered.
> [16:04:12:711311]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cylinderSolid:cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true) created and registered.
> [16:04:12:711326]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (cylinderWireframe:cylinderWireframe_rings_1_segments_32_halfLen_1) created and registered.
> [16:04:12:711341]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (icosphereSolid:icosphereSolid_subdivs_1) created and registered.
> [16:04:12:711376]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (icosphereWireframe:icosphereWireframe_subdivs_1) created and registered.
> [16:04:12:711391]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (uvSphereSolid:uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false) created and registered.
> [16:04:12:711410]:[Metadata] AssetAttributesManager.cpp(121)::createObject : Asset attributes (uvSphereWireframe:uvSphereWireframe_rings_16_segments_32) created and registered.
> [16:04:12:711419]:[Metadata] AssetAttributesManager.cpp(110)::AssetAttributesManager : Built default primitive asset templates : 12
> [16:04:12:711604]:[Metadata] SceneDatasetAttributesManager.cpp(35)::createObject : File (default) not found, so new default dataset attributes created  and registered.
> [16:04:12:711613]:[Metadata] MetadataMediator.cpp(120)::createSceneDataset : Dataset default successfully created.
> [16:04:12:711622]:[Metadata] AttributesManagerBase.h(380)::createFromJsonOrDefaultInternal : <Physics Manager>: Proposing JSON name : ./data/default.physics_config.json from original name : ./data/default.physics_config.json| This file exists.
> [16:04:12:711662]:[Metadata] PhysicsAttributesManager.cpp(26)::createObject : JSON Configuration File (./data/default.physics_config.json) based physics manager attributes created and registered.
> [16:04:12:711670]:[Metadata] MetadataMediator.cpp(203)::setActiveSceneDatasetName : Previous active dataset  changed to default successfully.
> [16:04:12:711676]:[Metadata] MetadataMediator.cpp(175)::setCurrPhysicsAttributesHandle : Old physics manager attributes  changed to ./data/default.physics_config.json successfully.
> [16:04:12:711683]:[Metadata] MetadataMediator.cpp(66)::setSimulatorConfiguration : Set new simulator config for scene/stage : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb and dataset : default which is currently active dataset.
> Renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2 by NVIDIA Corporation
> OpenGL version: 4.6.0 NVIDIA 515.65.01
> Using optional features:
>     GL_ARB_vertex_array_object
>     GL_ARB_ES2_compatibility
>     GL_ARB_separate_shader_objects
>     GL_ARB_robustness
>     GL_ARB_texture_storage
>     GL_ARB_invalidate_subdata
>     GL_ARB_texture_storage_multisample
>     GL_ARB_multi_bind
>     GL_ARB_direct_state_access
>     GL_ARB_get_texture_sub_image
>     GL_ARB_texture_filter_anisotropic
>     GL_KHR_debug
> Using driver workarounds:
>     no-forward-compatible-core-context
>     nv-egl-incorrect-gl11-function-pointers
>     no-layout-qualifiers-on-old-glsl
>     nv-zero-context-profile-mask
>     nv-implementation-color-read-format-dsa-broken
>     nv-cubemap-inconsistent-compressed-image-size
>     nv-cubemap-broken-full-compressed-image-query
>     nv-compressed-block-size-in-bits
> [16:04:14:887170]:[Metadata] MetadataMediator.cpp(297)::getSceneInstanceAttributesByName : Dataset : default has no preloaded SceneInstanceAttributes or StageAttributes named : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb so loading/creating a new StageAttributes with this name, and then creating a SceneInstanceAttributes with the same name that references this stage.
> [16:04:14:887200]:[Metadata] AttributesManagerBase.h(380)::createFromJsonOrDefaultInternal : <Stage Template>: Proposing JSON name : data/scene_datasets/habitat-test-scenes/skokloster-castle.stage_config.json from original name : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb| This file does not exist.
> [16:04:14:887258]:[Metadata] AbstractObjectAttributesManagerBase.h(184)::createObject : File (data/scene_datasets/habitat-test-scenes/skokloster-castle.glb) exists but is not a recognized config filename extension, so new default Stage Template attributes created and registered.
> [16:04:14:887291]:[Metadata] SceneDatasetAttributes.cpp(47)::addNewSceneInstanceToDataset : Dataset : 'default' : Stage Attributes 'data/scene_datasets/habitat-test-scenes/skokloster-castle.glb' specified in Scene Attributes exists in dataset library.
> [16:04:14:887299]:[Metadata] SceneDatasetAttributes.cpp(84)::addNewSceneInstanceToDataset : Dataset : 'default' : Lighting Layout Attributes 'no_lights' specified in Scene Attributes but does not exist in dataset, so creating.
> [16:04:14:887307]:[Metadata] AttributesManagerBase.h(380)::createFromJsonOrDefaultInternal : <Lighting Layout>: Proposing JSON name : no_lights.lighting_config.json from original name : no_lights| This file does not exist.
> [16:04:14:887320]:[Metadata] LightLayoutAttributesManager.cpp(36)::createObject : File (no_lights) not found, so new default light layout attributes created and registered.
> [16:04:14:887329]:[Sim] Simulator.cpp(237)::createSceneInstance : Navmesh file location in scene instance : data/scene_datasets/habitat-test-scenes/skokloster-castle.navmesh
> [16:04:14:887339]:[Sim] Simulator.cpp(242)::createSceneInstance : Loading navmesh from data/scene_datasets/habitat-test-scenes/skokloster-castle.navmesh
> [16:04:14:887353]:[Nav] PathFinder.cpp(852)::loadNavMesh : NavMeshSettings aren't present, guessing that they are the default
> [16:04:14:887416]:[Sim] Simulator.cpp(244)::createSceneInstance : Navmesh Loaded.
> [16:04:14:887433]:[Scene] SceneGraph.h(85)::createDrawableGroup : Created DrawableGroup: 
> [16:04:14:887442]:[Assets] ResourceManager.cpp(297)::loadSemanticSceneDescriptor : SceneInstance : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb proposed Semantic Scene Descriptor filename : data/scene_datasets/habitat-test-scenes/skokloster-castle.scn
> [16:04:14:887473]:[Assets] ResourceManager.cpp(1652)::ConfigureImporterManagerGLExtensions : Importing Basis files as BC7.
> [16:04:14:887642]:[Sim] Simulator.cpp(302)::createSceneInstance : Using scene instance-specified Light key : - no_lights -
> [16:04:14:887655]:[Metadata] MetadataMediator.cpp(66)::setSimulatorConfiguration : Set new simulator config for scene/stage : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb and dataset : default which is currently active dataset.
> [16:04:14:887672]:[Sim] Simulator.cpp(412)::instanceStageForSceneAttributes : Start to load stage named : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb with render asset : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb and collision asset : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
> [16:04:14:887711]:[Assets] ResourceManager.cpp(691)::createStageAssetInfosFromAttributes : Frame :{"up":[0,0,1],"front":[0,1,0],"origin":[0,0,0]} for render mesh named : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb|{"up":[0,0,1],"front":[0,1,0],"origin":[0,0,0]} for semantic mesh named :  with type specified as semantic|Semantic Txtrs : False
> [16:04:14:887719]:[Assets] ResourceManager.cpp(507)::loadStage : Start load render asset data/scene_datasets/habitat-test-scenes/skokloster-castle.glb .
> [16:04:14:887724]:[Assets] ResourceManager.cpp(973)::loadStageInternal : Attempting to load stage data/scene_datasets/habitat-test-scenes/skokloster-castle.glb 
> [16:04:14:887731]:[Assets] ResourceManager.cpp(855)::loadRenderAsset : Loading general asset named: data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
> [16:04:14:887736]:[Assets] ResourceManager.cpp(1652)::ConfigureImporterManagerGLExtensions : Importing Basis files as BC7.
> [16:04:14:887452]:[Assets] ResourceManager.cpp(344)::loadSemanticSceneDescriptor : SSD File Naming Issue! Neither SceneInstanceAttributes-provided name : data/scene_datasets/habitat-test-scenes/skokloster-castle.scn  nor constructed filename : data/scene_datasets/habitat-test-scenes/info_semantic.json exist on disk.
> [16:04:15:595858]:[Assets] ResourceManager.cpp(2089)::loadMaterials : Building 2 materials for asset named 'skokloster-castle.glb' : 
> [16:04:15:595931]:[Assets] ResourceManager.cpp(2194)::loadMaterials : Idx 00:Flat.
> [16:04:15:595948]:[Assets] ResourceManager.cpp(2194)::loadMaterials : Idx 01:Flat.
> [16:04:15:658266]:[Sim] Simulator.cpp(471)::instanceStageForSceneAttributes : 
> 
> The active scene does not contain semantic annotations : activeSemanticSceneID_ = 0  
> 
> 2023-01-10 16:04:15,660 Initializing task Nav-v0
> [16:04:15:658208]:[Sim] Simulator.cpp(439)::instanceStageForSceneAttributes : Successfully loaded stage named : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb
> [16:04:15:658286]:[Sim] Simulator.cpp(205)::reconfigure : CreateSceneInstance success == true for active scene name : data/scene_datasets/habitat-test-scenes/skokloster-castle.glb  with renderer.
> Environment creation successful
> [16:04:15:674615]:[Physics] PhysicsManager.cpp(50)::~PhysicsManager : Deconstructing PhysicsManager
> [16:04:15:674658]:[Scene] SceneManager.h(25)::~SceneManager : Deconstructing SceneManager
> [16:04:15:674690]:[Scene] SceneGraph.h(25)::~SceneGraph : Deconstructing SceneGraph
> [16:04:15:674922]:[Sensor] Sensor.cpp(69)::~Sensor : Deconstructing Sensor
> [16:04:15:674936]:[Sensor] Sensor.cpp(69)::~Sensor : Deconstructing Sensor
> Traceback (most recent call last):
>   File "/home/[MyUserName]/habitat-lab/examples/example_pointnav.py", line 30, in <module>
>     example()
>   File "/home/[MyUserName]/habitat-lab/examples/example_pointnav.py", line 19, in example
>     observations = env.reset()  # noqa: F841
>   File "/home/[MyUserName]/habitat-lab/habitat-lab/habitat/core/env.py", line 260, in reset
>     self.reconfigure(self._config)
>   File "/home/[MyUserName]/habitat-lab/habitat-lab/habitat/core/env.py", line 345, in reconfigure
>     self._sim.reconfigure(self._config.simulator)
>   File "/home/[MyUserName]/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 451, in reconfigure
>     self._update_agents_state()
>   File "/home/[MyUserName]/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 395, in _update_agents_state
>     agent_id,
>   File "/home/[MyUserName]/habitat-lab/habitat-lab/habitat/sims/habitat_simulator/habitat_simulator.py", line 593, in set_agent_state
>     agent.set_state(new_state, reset_sensors)
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim/agent/agent.py", line 255, in set_state
>     self.body.object.rotation = quat_to_magnum(state.rotation)
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/habitat_sim/utils/common.py", line 49, in quat_to_magnum
>     return mn.Quaternion(quat.imag, quat.real)
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/omegaconf/listconfig.py", line 185, in __getattr__
>     "ListConfig does not support attribute access"
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/omegaconf/base.py", line 237, in _format_and_raise
>     type_override=type_override,
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
>     _raise(ex, cause)
>   File "/home/[MyUserName]/anaconda3/envs/habitat/lib/python3.7/site-packages/omegaconf/_utils.py", line 797, in _raise
>     raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
> omegaconf.errors.ConfigAttributeError: ListConfig does not support attribute access
>     full_key: habitat.simulator.agents.main_agent.start_rotation[imag]
>     reference_type=List[float]
>     object_type=list
> [16:04:15:674960]:[Scene] SemanticScene.h(47)::~SemanticScene : Deconstructing SemanticScene
> [16:04:15:691945]:[Gfx] Renderer.cpp(72)::~Impl : Deconstructing Renderer
> [16:04:15:692005]:[Gfx] WindowlessContext.h(17)::~WindowlessContext : Deconstructing WindowlessContext
> [16:04:15:941496]:[Sim] Simulator.cpp(66)::~Simulator : Deconstructing Simulator
> 
> Process finished with exit code 1

**Comment by Yuchen-Song** [comment]
My `omegaconf` version is 2.3.0

**Comment by vincentpierre** [comment]
Hi @Yuchen-Song , 
I was unable to reproduce this on my machine on the latest v0.2.3 version.
Did you recently install habitat-sim? It looks like your habitat-sim and habitat-lab versions are not the same. Could you try reinstalling habitat-sim to the latest v0.2.3?
Thank you.

**Comment by Yuchen-Song** [comment]
Thank you, @vincentpierre 
When I reinstalled the 0.2.3 version of habitat-sim, the probelm no longer occurs.
BTW, the default install command for habitat-sim gets 0.2.2, for anyone who may face the same problem, should specify the version habitat-sim==0.2.3 (or the same version as habitat-lab) to avoid this.
