### ISSUE TITLE
Habitat.config 

### ISSUE THREAD

**Issue by JaechangKo** [facebookresearch/habitat-lab#1077]
For this tutorial session: https://www.youtube.com/watch?v=KbbfD7RlJLM&list=PLGywud_-HlCORC0c4uj97oppQrGiB6JNy
When I run the code 'Path Setup and Imports', habitat.config error doesn't allow me to move forward. Is this happened because of the incompatibility of TensorFlow version?

ImportError: cannot import name 'Config' from 'habitat.config' (/content/habitat-lab/habitat-lab/habitat/config/init.py)

Can some one let me know how to deal with this??

Error Message:
ImportError Traceback (most recent call last)
in
26 import habitat
27 import habitat_sim
---> 28 from habitat.config import Config
29 from habitat.core.registry import registry
30 from habitat_sim.utils import common as ut

ImportError: cannot import name 'Config' from 'habitat.config' (/content/habitat-lab/habitat-lab/habitat/config/init.py)
![123](https://user-images.githubusercontent.com/10793897/211986448-a7c80612-2aa3-41f9-a2a1-7916f5296f7b.JPG)

**Comment by rpartsey** [comment]
Duplicates https://github.com/facebookresearch/habitat-lab/issues/1074.
