### ISSUE TITLE
Failed to import habitat_sim following tutorial ECCV 2020: Navigation

### ISSUE THREAD

**Issue by Yuhanelle** [facebookresearch/habitat-lab#1089]
Hi, I followed the turotial ECCV 2020: Navigation in colab and I always receive this error when I run the code. I tried to change the path, but it didn't work. 

![image](https://user-images.githubusercontent.com/91812376/213791934-77fb600d-5075-44d2-982a-5b379ed83878.png)

Can anyone help me with this? Thank you in advance.

**Comment by rpartsey** [comment]
Hi @Yuhanelle check out [this issue](https://github.com/facebookresearch/habitat-sim/issues/1818). There is a known problem with Colab. Try the solution proposed there and let me know if there are more issues.

**Comment by aclegg3** [comment]
Note we have stopped supporting colab and converted tutorials to local Jupyter notebooks instead.
