### ISSUE TITLE
Should `VelocityControlActionConfig` be added to the ConfigStore

### ISSUE THREAD

**Issue by luisenp** [facebookresearch/habitat-lab#1115]
[This](https://github.com/facebookresearch/habitat-lab/blob/f64ca16901947947cb5a74ede34e5325f2b9f4fc/habitat-lab/habitat/config/default_structured_configs.py#L156) config option doesn't seem to be added to the config store, is this deliberate? I was trying to do something like the following:
```yaml
@package _global_
defaults:
  - /habitat/task/actions:
    - velocity_control
```
However, I had to add the following to the default configs to make this work (I didn't see any existing entries for this config option)
```python
cs.store(
    package="habitat.task.actions.velocity_control",
    group="habitat/task/actions",
    name="velocity_control",
    node=VelocityControlActionConfig,
)
```
Do let me know if this is not the intended way for this to be used. Thanks.

cc @jimmytyyang @KRobG

**Comment by jimmytyyang** [comment]
Thanks for reporting this. I think this is not intended

**Comment by luisenp** [comment]
In case it's helpful, I made a PR with the fix I proposed above.
