### ISSUE TITLE
Use shortest path greedy follower from habitat-sim for shortest path example

### ISSUE THREAD

**Issue by mathfac** [facebookresearch/habitat-lab#140]
We have `make_greedy_follower(self, agent_id: int = 0, goal_radius: float = None)` method from habitat-sim which is faster way to generate shortest path:
https://github.com/facebookresearch/habitat-sim/blob/master/habitat_sim/simulator.py#L167
It can throw an error if there is no shortest path between points.
That would be great to show how to work with in [our shortest_path example](https://github.com/facebookresearch/habitat-api/blob/master/examples/shortest_path_follower_example.py).

**Comment by Yash621** [comment]
@mathfac can I work on this ?

**Comment by erikwijmans** [comment]
This has already been done and should have been closed.
