### ISSUE TITLE
AttributeError: 'HabitatSim' object has no attribute '_initialized' & 'habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration' object has no attribute 'navmesh_settings'

### ISSUE THREAD

**Issue by etri-jeon0123** [facebookresearch/habitat-lab#1465]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.2.4
Habitat-Sim: v0.2.4

Currently, we are following the "Habitat Lab Demo" code.
It is the same problem as the **"AttributeError: 'HabitatSim' object has no attribute '_initialized' #1448"** problem in GitHub and shares a detailed error.

**How did you install the code?**
: It was installed following the official tutorial, and the Habitat-sim works perfectly.

**Are you using a conda env?**
: I did so because I had to use a Conda virtual environment if I followed the official tutorial.

**What python version are you using?**
: The installation required by the official tutorial's conda environment was performed as follows.
[ conda create -n habitat python=3.9 cmake=3.14.0 ]

**What data do you use?**
: The data downloaded [point goal navigation(MatterPort3D)] dataset from the link below.
https://github.com/facebookresearch/habitat-lab/blob/main/DATASETS.md 

## ❓ Questions and Help
I don't think there is any problem with the environment, but what is the problem at the moment?

1. AttributeError: 'habitat_sim._ext.habitat_sim_bindings.SimulatorConfiguration' object has no attribute 'navmesh_settings'
2. AttributeError: 'HabitatSim' object has no attribute '_initialized'

![Screenshot from 2023-07-25 10-07-51](https://github.com/facebookresearch/habitat-lab/assets/121843576/37ef0830-f41f-4d1a-b7a8-f333f156d2d3)

**Comment by aclegg3** [comment]
@etri-jeon0123 you proposed a solution in #1448 so I'll close this one.

**Comment by xiefujing** [comment]
For me, it is because the required attribute is not found, in your case the 'navmesh_setting' is not found in your config file, so the 'close' function is called. In my case, after I have all the required attribute in my config file, it works.
