### ISSUE TITLE
Missing objectnav_mp3d_v1.zip Download Link

### ISSUE THREAD

**Issue by xwy-bit** [facebookresearch/habitat-lab#1558]
Thank you for your impressive work!

![image](https://github.com/facebookresearch/habitat-lab/assets/56917268/4f936c5e-51cb-4541-8278-1c2fe36f91da)

I was attempting to download the MatterPort3D dataset for the object goal task and encountered an issue where the download link 
appears to be broken. This leads to the following page:
![image](https://github.com/facebookresearch/habitat-lab/assets/56917268/659ab5bb-830d-4739-bfaf-2c784c917d88)

**Comment by xwy-bit** [comment]
I have identified the issue. The correct source address should be: https://dl.fbaipublicfiles.com/habitat/data/datasets/objectnav/m3d/v1/objectnav_mp3d_v1.zip. Please note that it's "m3d," not "mp3d."

**Comment by dhruvbatra** [comment]
Thanks!
