### ISSUE TITLE
How to use habitat-lab with HSSD-hab dataset?

### ISSUE THREAD

**Issue by wzcai99** [facebookresearch/habitat-lab#1608]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.2.5
Habitat-Sim: v0.2.5
## ❓ Questions and Help
Hi, I am trying to run some object-nav episodes with hssd-hab and ai2thor scenes, but it seems that the rendered images (from observation['image']) are not working well. It seems that it only loads the geometries without textures, could you please give me some suggestions, thank you very much. 

<img width="701" alt="image" src="https://github.com/facebookresearch/habitat-lab/assets/115710611/16d2e6ff-7e70-475a-901e-2a3ec8e26eed">

**Comment by aclegg3** [comment]
Hey @wzcai99, we've made significant improvements in rendering over the last few months. If you are using `stable` or`v0.2.5` tags, then you are not getting the best experience. I suggest trying with habitat-sim `main` or nightly conda build instead.

**Comment by wzcai99** [comment]
@aclegg3 Following your suggestion, I got much better rendered images like this. 
<img width="638" alt="image" src="https://github.com/facebookresearch/habitat-lab/assets/115710611/e8062c8a-d6e7-47d1-9f0b-1bd61b34899b">
<img width="748" alt="image" src="https://github.com/facebookresearch/habitat-lab/assets/115710611/baec0de5-5c10-4671-a740-ae183cfa5c6f">

But it still seems not as realistic as the teasor video in https://github.com/3dlg-hcvc/hssd, is it a trade-off between the render quality and the simulation efficiency or am I doing something wrong in the configuration?

**Comment by aclegg3** [comment]
Hey @wzcai99,

You shouldn't expect to match the fidelity from the video in simulation. A couple of reasons:
1. that video is using a raw un-compressed version of the assets found [here](https://huggingface.co/datasets/hssd/hssd-scenes).
2. the video was rendered offline with Blender at a speed which would not support inner-loop RL learning compute constraints.

The hssd-hab version uses compressed assets and a very efficient rendering pipeline to produce images at rates acceptable for onilne ML applications and takes some hits on optics to achieve that.

It does look like you could [turn on HBAO](https://aihabitat.org/docs/habitat-sim/habitat_sim.sim.SimulatorConfiguration.html#enable_hbao) to get shadows on top of the quality you are showing in the images here, however.

**Comment by wzcai99** [comment]
@aclegg3 Thank you, I got it.
