### ISSUE TITLE
Implement Task Action Wrapper for Continuous Control

### ISSUE THREAD

**Issue by krishanrana** [facebookresearch/habitat-lab#165]
I would like to experiment an idea with TD3 and wanted to know if it would be possible to use a continuous action space for the agent, and how to got about setting it up.

**Comment by abhiskk** [comment]
hi, can you give more details about what exactly you mean by a continuous action space?

**Comment by krishanrana** [comment]
Hi abhishek, I would like to utilise an action space consisting of linear velocity and angular velocity as opposed to the discrete actions (turn left, go forward etc) in order to control my agent in the environment.

**Comment by erikwijmans** [comment]
The core of habitat-sim does support continuous action spaces (the collision detection logic makes no assumptions about discrete actions) but the API to properly support continuous actions (both habtiat-api and in the simulator itself) aren't there.

**Comment by huangxueqin123** [comment]
Hi krishanrana, I also have the same problem.Have you solved it?

> Hi abhishek, I would like to utilise an action space consisting of linear velocity and angular velocity as opposed to the discrete actions (turn left, go forward etc) in order to control my agent in the environment.

**Comment by mathfac** [comment]
Hi @huangxueqin123 and @krishanrana,
We have continuous actions space for [habitat-api Task Actions](https://github.com/facebookresearch/habitat-api/blob/master/habitat/tasks/nav/nav.py#L842). You can add your own task action `move(velocity, angular_velocity)` and set/calculate agent position accordingly in `Task.step` method.

Our plan is to add native support of continues actions to the Habitat Simulator till the end of the year.

cc @aclegg3

**Comment by Skylion007** [comment]
@mathfac Do we have any updates on this front?

**Comment by aclegg3** [comment]
We have an example of using continuous actions in Habitat-sim in [this tutorial](https://aihabitat.org/docs/habitat-sim/rigid-object-tutorial.html#continuous-control-on-navmesh). You'd just need to implement the task action wrapper for this I think.

**Comment by rpartsey** [comment]
@ASzot do I understand correctly that such functionality is already implemented in habitat-lab as the [BaseVelAction](https://github.com/facebookresearch/habitat-lab/blob/380ac0a7d8c4ead1532f109b15d329473212eae9/habitat/tasks/rearrange/actions/actions.py#L227)?

**Comment by ASzot** [comment]
@rpartsey that's correct. Continuous actions are very well integrated in Habitat now.
