### ISSUE TITLE
Request for the social navigation/rearrangement dataset

### ISSUE THREAD

**Issue by XinyuSun** [facebookresearch/habitat-lab#1650]
I'm interested in the social navigation and social rearrangement tasks released with habitat-3.0, when would you consider releasing the dataset?

**Comment by xavierpuigf** [comment]
The datasets are already available under hab3-episodes (see [here](https://huggingface.co/datasets/ai-habitat/hab3_episodes)). Our README contains instructions to download and test the datasets.

Link: https://github.com/facebookresearch/habitat-lab/tree/main/habitat-baselines#habitat-30-multi-agent-training
