### ISSUE TITLE
AssertionError: move_obj_reward measure requires object_to_goal_distance 

### ISSUE THREAD

**Issue by Li-ChangHao** [facebookresearch/habitat-lab#1652]
When I use the command：

 `scripts/hab3_bench/bench_runner.sh`

I got an error: 

```
AssertionError: move_obj_reward measure requires object_to_goal_distance
                 listed in the measures list in the config.

```

Then I added object_to_goal_distance in habitat-lab/habitat-lab/habitat/config/benchmark/rearrange/hab3_bench/single_agent_bench.yaml

<img width="310" alt="image" src="https://github.com/facebookresearch/habitat-lab/assets/60425170/37beefa8-fa6b-46e1-960b-cf43168e1bed">

Then an error is reported: 

```
AssertionError: move_obj_reward measure requires ee_to_object_distance
                listed in the measures list in the config.
```
So I I added ee_to_object_distance in habitat-lab/habitat-lab/habitat/config/benchmark/rearrange/hab3_bench/single_agent_bench.yaml

Then got an error:

`hydra.errors.MissingConfigException: In 'benchmark/rearrange/hab3_bench/single_agent_bench': Could not load 'habitat/task/measurements/ee_to_object_distance'.`

Is there any solution?

**Comment by duanyiqun** [comment]
Hi Changhao, I'm so excited you met the same problem with me. Have you solved the problem?
Any help would be very appreciated.

**Comment by ruddradev** [comment]
Hi @duanyiqun : You need to change line 2247 in habitat-lab/habitat/config/default_structured_configs.py from - 
name="end_effector_to_object_distance"
to -
name="ee_to_object_distance"
