### ISSUE TITLE
issue abou checkpoint on social navigation in habitat 3.0

### ISSUE THREAD

**Issue by Li-ChangHao** [facebookresearch/habitat-lab#1683]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v3.0 or master?

I want to know if any checkpoint has been released about social navigation in habitat 3.0? In the meantime, is there any code about Heuristic Expert released?

**Comment by jimmytyyang** [comment]
Hi @Li-ChangHao! Thank you so much for your interest in social navigation. We have released the checkpoint, and you can follow the [readme](https://github.com/facebookresearch/habitat-lab/tree/main/habitat-baselines#readme) to download and run the code. Please use the latest habitat 3.0 `main` And yes, we aim to release the Heurstic Expert in the near future ASAP. Thank you, and please let me know if you run into any issues.
