### ISSUE TITLE
error about Key 'count_coll_pen' not in 'SocialNavReward'

### ISSUE THREAD

**Issue by Li-ChangHao** [facebookresearch/habitat-lab#1709]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.3.0

Habitat-Sim: v0.3.0

tag：stable

## 🐛 Bug

When I run the code according to the readme, an error occurs：Key 'count_coll_pen' not in 'SocialNavReward'。

The following is the main error message：

<img width="869" alt="image" src="https://github.com/facebookresearch/habitat-lab/assets/60425170/7652b4ac-f18d-417d-975e-accd73651926">

**Comment by jimmytyyang** [comment]
Hi @Li-ChangHao! Could you please try to `git pull origin main` to make sure you are using the latest habitat-lab `main`? The stable version might not work. In addition, would you please also paste your latest commit hash for habitat-lab? Thank you!

**Comment by Li-ChangHao** [comment]
latest commit hash：afe4058a7f8aa5ab71a133575cdaa79f0308af6a

**Comment by Li-ChangHao** [comment]
it works, many thanks
