### ISSUE TITLE
Strange black patches in rendering observations in hm3d v1 scenes

### ISSUE THREAD

**Issue by verityw** [facebookresearch/habitat-lab#1921]
I noticed that there are strange black rectangular patches in observations from scenes in hm3d v1. This seems to be *different* from the black missing mesh rendering spots mentioned [here](https://github.com/facebookresearch/habitat-lab/issues/402) -- the patches are consistently rectangular, rather than irregularly shaped like in said issue. Additionally, the patches are differently sized and distributed when the resolution changes -- I've attached images of the same views in the same scene at two resolutions, and the higher resolution one has more small patches.

In the past, I've only used v2 (which only has the irregular mesh black patches, not the rectangular ones displayed below). Thus, I'm not sure if this is an issue with just hm3d v1.

[Here's a short Jupyter notebook that generated the below images.](https://drive.google.com/file/d/1oRESFums-_GYUEy3ZK34L4Oq1OxCWc7-/view?usp=sharing)

Any help would be greatly appreciated!

![image](https://github.com/facebookresearch/habitat-lab/assets/39648931/5aa9d4de-02cf-4cbb-8218-785b75a28aab)
![image](https://github.com/facebookresearch/habitat-lab/assets/39648931/5965b009-c7f1-4457-ad1d-72d4e728c339)

## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.3.1
Habitat-Sim: v0.3.1

**Comment by aclegg3** [comment]
This is almost definitely a graphics driver issue. 
@0mdc FYI

This may be related to: https://github.com/facebookresearch/habitat-sim/issues/1987 or https://github.com/facebookresearch/habitat-sim/issues/2310 (if using A100 GPU).

You may find some debugging tips here useful: https://github.com/facebookresearch/habitat-lab/blob/main/TROUBLESHOOTING.md

**Comment by verityw** [comment]
Aha, it is using an A100. Weird, I've never had this issue in the past before. Let me check out those links...

**Comment by verityw** [comment]
reboot and nvidia driver reinstall worked btw :) thanks for the help!

**Comment by jdiazram** [comment]
Hi @verityw. I have been trying to use hm3d in Habitat-Lab without good results. Is it possible to share the code on how to use hm3d in Habitat-Lab? This is the link you shared, but it is broken (https://drive.google.com/file/d/1oRESFums-_GYUEy3ZK34L4Oq1OxCWc7-/view?usp=sharing)
Thanks
