### ISSUE TITLE
What does ``access_mgr`` in ``habitat-baselines/rl/ppo`` stands for?

### ISSUE THREAD

**Issue by Yonggie** [facebookresearch/habitat-lab#1966]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.3.1
Habitat-Sim: v0.3.1
## ❓ Questions and Help
Hi, I see this is the base class of agent used in ``ppo_trainer``. What does ``agent access mgr`` mean? Any related full name paper or method, especially ``mgr``?
![图片](https://github.com/facebookresearch/habitat-lab/assets/31330044/717b8b71-5c1a-49fe-80ca-a956169a0dcd)

**Comment by xavierpuigf** [comment]
Hi! This stands for agent access manager. This is a class to manage RL functionalities for agents, this is common to most RL algorithms, and not particular to any paper. It allows to access the episodes rollouts from an agent so that we can do experience replay, create policies etc.
