### ISSUE TITLE
Question about missing scene rendering 

### ISSUE THREAD

**Issue by zoeyliu1999** [facebookresearch/habitat-lab#1997]
Dear authors, thank you for your excellent work!

I am trying to render a scene with a specified motion file. I removed the following line from the code:

https://github.com/facebookresearch/habitat-lab/blob/01f33323692dfe573d3b4072a3e90c3d5f3c3a5c/test/test_humanoid.py#L334

As a result, the default scene should be `data/scene_datasets/habitat-test-scenes/skokloster-castle.glb`. I expected the humanoid to walk in the Skokloster Castle, but the scene is missing in the visualization video.

Here is one frame from the video:

<img width="628" alt="image" src="https://github.com/facebookresearch/habitat-lab/assets/53820204/0b6db80a-084e-4a9a-99d9-d0d327c59638">

Am I missing something that is causing the rendering to fail? Any suggestions or guidance would be greatly appreciated. Thank you!

**Comment by xavierpuigf** [comment]
I think that the scene is still there, but it is in a different location. You can verify that the scene is created by running this before the test ends:

```
from habitat.sims.habitat_simulator.debug_visualizer import DebugVisualizer
import cv2
        
IM_W = 256
dbv = DebugVisualizer(sim, resolution=(IM_W, IM_W))
dbo = dbv.peek("scene")
img_scene = np.array(dbo.get_image())[:, :, [2,1,0]]
cv2.imwrite("res.png", img_scene)
         
```
You should get this, which is an overlap between the scene and the floor object we create.
<img width="887" alt="image" src="https://github.com/facebookresearch/habitat-lab/assets/4203263/dd30ae03-cb0f-49ec-94ec-f4d75402a77c">

You can get the location and bounds of the scene by running:

```
 sim.get_active_scene_graph().get_root_node().cumulative_bb
```

**Comment by zoeyliu1999** [comment]
> I think that the scene is still there, but it is in a different location. You can verify that the scene is created by running this before the test ends:
> 
> ```
> from habitat.sims.habitat_simulator.debug_visualizer import DebugVisualizer
> import cv2
>         
> IM_W = 256
> dbv = DebugVisualizer(sim, resolution=(IM_W, IM_W))
> dbo = dbv.peek("scene")
> img_scene = np.array(dbo.get_image())[:, :, [2,1,0]]
> cv2.imwrite("res.png", img_scene)
>          
> ```
> 
> You should get this, which is an overlap between the scene and the floor object we create. <img alt="image" width="887" src="https://private-user-images.githubusercontent.com/4203263/346238068-dd30ae03-cb0f-49ec-94ec-f4d75402a77c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMzM5MjcsIm5iZiI6MTcyMDIzMzYyNywicGF0aCI6Ii80MjAzMjYzLzM0NjIzODA2OC1kZDMwYWUwMy1jYjBmLTQ5ZWMtOTRlYy1mNGQ3NTQwMmE3N2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDZUMDI0MDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGViZGYzOWQ0ZGRhZGU2ZDNiMjliZTEwYTc1MWViYzJlOTJjMWFkNmZlMWY4YzAwMmE4ODQ2NjNiMWM2NmU1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZohZG0iXOf0veyR8mB3Yx6rAPbB7ay_mWU-TUDjXrmk">
> 
> You can get the location and bounds of the scene by running:
> 
> ```
>  sim.get_active_scene_graph().get_root_node().cumulative_bb
> ```

You are right! After running the `DebugVisualizer`, I observed exactly the overlap between the scene and the floor object.

<img width="517" alt="image" src="https://github.com/facebookresearch/habitat-lab/assets/53820204/93a51683-16c2-4f69-8290-965945746a7b">

The location and bounds of the scene are: `Range({-9.75916, -0.390077, 0.973852}, {8.56903, 6.83441, 25.5983})`. Does this mean I should retarget the location of the humanoid?

**Comment by xavierpuigf** [comment]
That's right! Retargeting should do
