### ISSUE TITLE
Pointgoal generator retry loop contains an error

### ISSUE THREAD

**Issue by edbeeching** [facebookresearch/habitat-lab#218]
## 🐛 Bug

When running the pointgoal generator the number_retries_per_target does not break from the loop when a compatible source position is found.

https://github.com/facebookresearch/habitat-api/blob/8c20adaaaddfbaee85dc9fe8b4b9f3d85a9a4ddb/habitat/datasets/pointnav/pointnav_generator.py#L130

## To Reproduce

Run the pointgoal example code.

## Expected behavior
The loop should break when the first compatible point is found.

Add the following code after line 140
```python
if is_compatible:
    break
```

**Comment by rpartsey** [comment]
This bug is already fixed.
