### ISSUE TITLE
Passing environment and simulator seed to the C++ bindings

### ISSUE THREAD

**Issue by devendrachaplot** [facebookresearch/habitat-lab#238]
## 🚀 Feature

Passing the habitat RLEnv and python Simulator seed to the C++ bindings so that functions like `self._env.sim.sample_navigable_point()` generate the same point after setting the sim seed using `self._env.sim.seed(seed)`

## Motivation
This will make many things reproducible, including generating datasets. It should help in benchmarking.

**Comment by mathfac** [comment]
@devendrachaplot, thank you for creating this issue. We have [the related issue on habitat-sim side](https://github.com/facebookresearch/habitat-sim/issues/44). Your request is rising the priority.
