### ISSUE TITLE
Implement Registry for policies for Habitat Baselines

### ISSUE THREAD

**Issue by mathfac** [facebookresearch/habitat-lab#404]
## 🚀 Feature

Implement Registry for policies([similar that we have for baselines](https://github.com/facebookresearch/habitat-api/blob/master/habitat_baselines/common/baseline_registry.py)) for Habitat Baselines than we can avoid patterns like [this](https://github.com/jacobkrantz/VLN-CE/blob/master/vlnce_baselines/dagger_trainer.py#L254).

## Motivation
Often we want to swap policy architecture, but use the same trainer.

**Comment by Skylion007** [comment]
Closed by #440
