### ISSUE TITLE
starting position

### ISSUE THREAD

**Issue by VladislavHrosinkov** [facebookresearch/habitat-lab#421]
## ❓ Questions and Help
Hello. I am just starting out with habitat, using the replica dataset. How can one select the starting location for the scene? I have my own config file, but I always start out far from the scene in a void near 0,0,0 and varying the starting location does not change my position much. What can I do?

**Comment by erikwijmans** [comment]
The scene coordinates can be fairly arbitrary, so (0, 0, 0) may not be sensible.  You can look at the code here for generating a pointnav dataset which will contain sensible starting points: https://github.com/facebookresearch/habitat-api/blob/master/habitat_baselines/rl/ddppo/data_generation/create_gibson_large_dataset.py
