### ISSUE TITLE
Standard interface for policy instantiation

### ISSUE THREAD

**Issue by rpartsey** [facebookresearch/habitat-lab#452]
## 🚀 Feature

Standard interface for policy instantiation.

## Motivation

As described in https://github.com/facebookresearch/habitat-lab/issues/404 it would be nice to be able to change the trainer's policy architecture. The motivation for this issue is to implement the standard interface for policy instantiation so that we can swap them dynamically and avoid hardcoded instantiation ([like](https://github.com/facebookresearch/habitat-lab/blob/4e875493769e0c1b756cf54e8ca5ef826d1ab49a/habitat_baselines/rl/ppo/ppo_trainer.py#L63) this and [this](https://github.com/facebookresearch/habitat-lab/blob/4e875493769e0c1b756cf54e8ca5ef826d1ab49a/habitat_baselines/rl/ddppo/algo/ddppo_trainer.py#L73)).

## Additional context

 The main policy registry functionality was implemented here https://github.com/facebookresearch/habitat-lab/pull/440.

**Comment by Skylion007** [comment]
Closed by #453
