### ISSUE TITLE
Upgrade gym to v0.17.2

### ISSUE THREAD

**Issue by dexter1691** [facebookresearch/habitat-lab#460]
## 🚀 Feature
The current gym version used in Habitat Lab is pretty old v0.10x. It'd be good to upgrade it to the latest version v0.17. 

## Motivation
One of the motivations was to be able to use something like Stable-Baselines 3 (https://github.com/DLR-RM/stable-baselines3) to run various RL algorithms and it assumes the latest Gym interface.

**Comment by Skylion007** [comment]
@dexter1691 This is fixed now. #498 should allow modern gym usage in a backwards compatible way. :D

**Comment by Skylion007** [comment]
Closed by #498
