### ISSUE TITLE
Duplicated lines of code

### ISSUE THREAD

**Issue by rpartsey** [facebookresearch/habitat-lab#464]
## 🐛 Bug

The following lines of code are repeated twice in the `Env`s `reset` method
```
if self._current_episode is not None:
    self._current_episode._shortest_path_cache = None
```

See lines 208 and 214  https://github.com/facebookresearch/habitat-lab/blob/e0807ed403902de78ee37b36766c2f06e5886fea/habitat/core/env.py#L208

**Comment by Skylion007** [comment]
Code deletion PR welcome.

**Comment by rpartsey** [comment]
Closed by https://github.com/facebookresearch/habitat-lab/pull/467.
