### ISSUE TITLE
Redundant env.close() method call

### ISSUE THREAD

**Issue by rpartsey** [facebookresearch/habitat-lab#465]
## 🐛 Bug

Redundant `env.close()` method call. 
See https://github.com/facebookresearch/habitat-lab/blob/358969e4a631915767c52a792b1d2fd6a33ec4b8/examples/example.py#L26

## Additional context

`close` method is called inside `__exit__`.
 See https://github.com/facebookresearch/habitat-lab/blob/e0807ed403902de78ee37b36766c2f06e5886fea/habitat/core/env.py#L307

**Comment by Skylion007** [comment]
Closed by #466
