### ISSUE TITLE
Object View points

### ISSUE THREAD

**Issue by saishankarn** [facebookresearch/habitat-lab#475]
Does every object in mp3d dataset have view points or are viewpoints only provided for the goal objects in every episode as given in the mp3d objectnav dataset ?

**Comment by Skylion007** [comment]
We calculate the viewpoints during dataset generation they aren't provided by the MP3D Dataset. We do this by looking for all points within 1 meters of the object where the object is visible.

**Comment by saishankarn** [comment]
thank you
