### ISSUE TITLE
Automated Task Dataset Download Feature

### ISSUE THREAD

**Issue by Skylion007** [facebookresearch/habitat-lab#489]
## 🚀 Feature

It would be nice if there was an API to automatically download the task datasets instead of having to extract them ourselves. Should be pretty easy to write, just not implemented at the moment. I envision there being a dictionary of sorts that maps to URLs or a special path prefix that tells you to download a dataset if it doesn't exist. Then it just calls requests and such to unzip the dataset.

## Motivation
* Just makes Habitat more friendly to use. Low PRI but useful if someone wants to contribute.

## Pitch
Makes Habitat-Lab more welcoming to new comers. Could extend the habitat_sim datasets download_tool.

**Comment by Skylion007** [comment]
Ping @aravwatwani if you are still interested in working on this.

**Comment by Yash621** [comment]
@Skylion007 can I work on this ?

**Comment by rpartsey** [comment]
@Skylion007 Looks like such API has been already implemented in [habitat-sim](https://github.com/facebookresearch/habitat-sim/blob/2662204daa6d6324ced92b7e9e0ae0365cef9e41/src_python/habitat_sim/utils/datasets_download.py#L573).
