### ISSUE TITLE
How to build continuous environment for navigation task ? 

### ISSUE THREAD

**Issue by Mingxiao-Li** [facebookresearch/habitat-lab#494]
## ❓ Questions and Help
Hi, I am wandering is there a tutorial about how to build a real-time interactive environment, like this demo https://aihabitat.org/demo/, for navigation .

**Comment by mathfac** [comment]
For simple keyboard interactive mode you can check [the example from our doc page](https://github.com/facebookresearch/habitat-lab/blob/7766bf5fdb70db2aede35d2eb1123662a485f7f8/docs/pages/quickstart.rst#example).

For closer reimplementation of the demo check the PR https://github.com/facebookresearch/habitat-lab/pull/187.
