### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Mingxiao-Li** [facebookresearch/habitat-lab#505]
## 🐛 Bug
ModuleNotFoundError: No module named 'habitat_baselines.common.utils'
Hi I successfully installed the habitat library, but then I got this error. 

## To Reproduce

1.
2.
3.

**Comment by Skylion007** [comment]
Please make sure to install with the --all flag in setup.py

**Comment by Moon-heart** [comment]
I also meet this error, how do you solve it? can you give me some advice?thanks
