### ISSUE TITLE
docker instructions

### ISSUE THREAD

**Issue by Prashant446** [facebookresearch/habitat-lab#514]
The instructions are pulling and running different images:
1. fairembodied/habitat:latest
2. fairhabitat/habitat:v1
Although both are similar, which one is preferred?

The docker container clone habitat-lab repo using its previous name "habitat-api". The docker instructions in README.md uses the new name.

**Comment by dhruvbatra** [comment]
>     fairembodied/habitat:latest
>    fairhabitat/habitat:v1
>    Although both are similar, which one is preferred?

CC: @abhiskk 

> The docker container clone habitat-lab repo using its previous name "habitat-api". The docker instructions in README.md uses the new name.

Ah, right. That is a typo, thanks for catching that. The instructions should say habitat-api (to be consistent with the docker). The docker is updated annually, so it expected to be significantly out of date.
