### ISSUE TITLE
How to set start position and goal position for shortest path follower? I want to use it to obtain my own dataset.

### ISSUE THREAD

**Issue by sekisyou0328** [facebookresearch/habitat-lab#520]
## ❓ Questions and Help
Hi,
I really want to know how to set start position and goal position for shortest path follower? I want to use it to obtain my own dataset .

**Comment by erikwijmans** [comment]
https://github.com/facebookresearch/habitat-lab/blob/master/examples/shortest_path_follower_example.py

The starting position is determined by where the agent is when you call `follower.get_next_action`.
