### ISSUE TITLE
using replica dataset

### ISSUE THREAD

**Issue by mmahdavian** [facebookresearch/habitat-lab#537]
Hi everyone and @erikwijmans 

I am trying to use replica dataset and I have used apartment_01.glb which I could find. I am using https://gist.github.com/erikwijmans/1c596183fb8de1e9afd80088b6b5c115 code to generate training dataset and I change the .glb file to the environment that I want. I need to change other replica dataset envs to be able to generate training data as well. But the replica dataset files are .ply format.Do you know how should I use them? Should I convert them to .glb and then use them or there is a way in habitat to use .ply files too.
By the way, I have tried to convert .ply to .glb by assimp. But when it tries to open it, the environment is all white and I get no error.

Thank You

**Comment by erikwijmans** [comment]
Closing in favor of https://github.com/facebookresearch/Replica-Dataset/issues/63
