### ISSUE TITLE
Error when executing python setup.py test

### ISSUE THREAD

**Issue by jsdd25** [facebookresearch/habitat-lab#541]
## ❓ Questions and Help

Hi guys!

I have installed `habitat-sim 0.1.6` and I have downloaded habitat-lab-stable with the version of 0.1.6. Then, I successfully run the example script `python examples/example.py` which in the end should print out: `Episode finished after 3 steps`.

However, when I executed the command `python setup.py test`, it happens error.

Here is the error I got:

============================= test session starts ==============================
platform linux -- Python 3.6.12, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/jin/habitat-lab-stable, configfile: setup.cfg, testpaths: test
plugins: cov-2.10.1, mock-3.3.1
collected 102 items / 1 error / 101 selected                                   

==================================== ERRORS ====================================
_______________ ERROR collecting test/test_baseline_trainers.py ________________
test/test_baseline_trainers.py:19: in <module>
    from habitat_baselines.common.base_trainer import BaseRLTrainer
<frozen importlib._bootstrap>:971: in _find_and_load
    ???
<frozen importlib._bootstrap>:951: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:894: in _find_spec
    ???
<frozen importlib._bootstrap_external>:1157: in find_spec
    ???
<frozen importlib._bootstrap_external>:1123: in _get_spec
    ???
<frozen importlib._bootstrap_external>:994: in __iter__
    ???
<frozen importlib._bootstrap_external>:982: in _recalculate
    ???
<frozen importlib._bootstrap_external>:978: in _get_parent_path
    ???
E   KeyError: 'habitat_baselines'

---------- coverage: platform linux, python 3.6.12-final-0 -----------
Coverage XML written to file coverage.xml

!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 2.94s ===============================

Could anyone help me with this? Thank you very much!

**Comment by mathfac** [comment]
Hi @jsdd25
Are you sure you installed habiat_baselines module as well with:
```
pip install -r requirements.txt
python setup.py develop --all
```
like mentioned in [the installation section](https://github.com/facebookresearch/habitat-lab#installation).

Feel free to close the issue was resolved.
