### ISSUE TITLE
About MP3D-EQA v1 test set

### ISSUE THREAD

**Issue by sekisyou0328** [facebookresearch/habitat-lab#542]
## ❓ Questions and Help
Hi
There are only train and val data in the eqa_mp3d_v1.zip datasets.
Can you provide the test data?

Thank you very much.

**Comment by mathfac** [comment]
Hi @sekisyou0328,
It was kept private to have an opportunity to create an independent benchmark like [this one](https://eval.ai/web/challenges/challenge-page/580/overview) where test split isn't publicly available.
