### ISSUE TITLE
ORB-SLAM Baseline

### ISSUE THREAD

**Issue by Jbwasse2** [facebookresearch/habitat-lab#565]
## ❓ Questions and Help
I am not sure if I am getting the correct results on the ORB-SLAM baseline. I managed to get ORB-SLAM running after making some changes to the code by following some hints in #270 as well as other code changes I had to make along the way (let me know if you'd like a PR). 

I changed the baseline experiment to run for 100 episodes instead of 10,000 and here are my results
{'distance_to_goal': 7.190535881593823, 'success': 0.02, 'spl': 0.019367131175261093}
This seemed pretty low so I wanted to reach out here to see if my expected results should be better. 

Debugging:
I have ran the "update_internal_state" over some collected trajcetories to create a map and I have noticed that "self.slam.get_tracking_state()" will frequently return LOST, causing the map that has been made so far to be deleted. My gut feeling is that the frames I am giving it are collected with action space (turn 30 degrees, move forward 0.25 meters) and I think that might be too big of a jump.

Edit - 1-17-2020
I made it so the map was built off of action space (6 degrees turn, 0.05 meters forward) and its not getting "LOST" anymore, but the map still isn't looking great.
[Trajectories Video](https://www.youtube.com/watch?v=_badXZGs_og)
[Top Down Video](https://www.youtube.com/watch?v=FcgREMnunQs)

Edit 1-25-2020
In the making of the map in update_state, there is a condition for stopping if the agent gets LOST. Currently I may get a LOST after adding a few trajectories to the map, but then it dies after getting LOST, I think there was something in the corresponding paper for this implementation about it getting LOST and then stopping. 

So here is the trick to solve this problem.... 

Just ignore it (so don't stop mapping when you hit the LOST). The mapper will eventually re localize itself.

**Comment by rpartsey** [comment]
The Issue was resolved by the Issue author. Solution is described in the edited Issue description.
> Edit 1-25-2020
So here is the trick to solve this problem....
Just ignore it (so don't stop mapping when you hit the LOST). The mapper will eventually re localize itself.
