### ISSUE TITLE
Long dataset load times

### ISSUE THREAD

**Issue by smorad** [facebookresearch/habitat-lab#568]
## ❓ Questions and Help
Habitat seems to load datasets much slower than when I used it a few months ago, at roughly 8-9 minutes on average. I'm using the provided `objectnav_mp3d.yaml` config. Is this to be expected? I'm running in a docker container with 192GiB memory 32 cores. The `scene_datasets` directory is bind-mounted from the host SSD into the container. 

`habitat-lab rev 7537389aaf5bbd3c3a8524c492c4d520311b9c9d`
`habitat-sim rev e199b997d518f266edb0feb0dc2aa290831fa3a6`

```
2021-01-20 11:34:59,101 Initializing dataset ObjectNav-v1
2021-01-20 11:42:27,118 initializing sim Sim-v0
```

Looking at `top`, Habitat pegs a CPU to 100% and slowly increases in memory size until it hits ~30 GB and then finishes loading.

**Comment by erikwijmans** [comment]
I am not aware of anything that would have changed load times significantly. Where you loading objectnav or pointnav previously?  The objectnav dataset is considerably heavier than the pointnav dataset
