### ISSUE TITLE
Possible Quaternion Syntax Bug in PointGoal

### ISSUE THREAD

**Issue by Jbwasse2** [facebookresearch/habitat-lab#591]
## ❓ Questions and Help
I wrote some code for my own purposes that was a copy/paste of the _compute_pointgoal function [found here](https://github.com/facebookresearch/habitat-lab/blob/b7a93bc493f7fb89e5bf30b40be204ff7b5570d7/habitat/tasks/nav/nav.py) and I noticed that it would give funny answers. 

The convention that I see used throughout habitat is that a quaternion is [x,y,z,w], but since this function uses the quaternion library it expects the quaternion to be of the form [w,x,y,z] in order to work. Would this cause issues for other parts of the habitat code that call this function?

**Comment by erikwijmans** [comment]
This is what helper functions like https://github.com/facebookresearch/habitat-lab/blob/master/habitat/utils/geometry_utils.py#L50 are for
