### ISSUE TITLE
Segmentation Fault (core dumped) when building environment

### ISSUE THREAD

**Issue by yuyecreus** [facebookresearch/habitat-lab#593]
Hello everybody :) 

I have set up the habitat-lab and habitat-sim environments in a local machine that runs Linux Ubuntu 20.04 LTS.

After setting up the conda environment and installing all the requirements I have been able to run the examples in the github repo (e.g python examples/example.py or python examples/example.py --scene /path/to/data/scene_datasets/habitat-test-scenes/skokloster-castle.glb). They work as expected. 

I have also been able to reproduce the demo scripts in https://aihabitat.org/docs/habitat-lab/quickstart.html and https://aihabitat.org/docs/habitat-lab/habitat-sim-demo.html

However, when I run the first two code snippets from the habitat-lab demo I get a seg.fault (core dumped) when building the environment. (https://aihabitat.org/docs/habitat-lab/habitat-lab-demo.html)

`
import habitat
import numpy as np
import random
import matplotlib.pyplot as plt

config = habitat.get_config(config_paths='./configs/tasks/pointnav_mp3d.yaml')
config.defrost()
config.DATASET.DATA_PATH = './data/datasets/pointnav/mp3d/v1/train/train.json.gz'
config.DATASET.SCENES_DIR = './data/scene_datasets/'
config.SIMULATOR.AGENT_0.SENSORS = ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
config.SIMULATOR.SEMANTIC_SENSOR.WIDTH = 256
config.SIMULATOR.SEMANTIC_SENSOR.HEIGHT = 256
config.SIMULATOR.TURN_ANGLE = 30
config.freeze()

env = habitat.Env(config=config)
`

Does anyone have any clue on what is going on here? 

Any help is much appreciated.  Thank you very much

**Comment by erikwijmans** [comment]
Please make sure logging isn't disabled and post the logging messages.
