### ISSUE TITLE
Question on how to generate object-goal datasets for gibson tiny

### ISSUE THREAD

**Issue by JAYH13947** [facebookresearch/habitat-lab#599]
## ❓ Questions and Help
Hello, I am working on a habitat project where I need to generate my own object-goal datasets for gibson tiny dataset.
I have read the instructions of how to make a pointgoal task dataset written in https://gist.github.com/erikwijmans/1c596183fb8de1e9afd80088b6b5c115 as cited in #293. In the same way, I want to generate my own object goal dataset for gibson tiny dataset.
Also, in the object goal dataset for mp3d, I see that it includes the 'best_view_point' for the nearest object in the goal object category. I want to know how you implemented it.

Best regards.

**Comment by rpartsey** [comment]
Duplicates https://github.com/facebookresearch/habitat-lab/issues/559.
