### ISSUE TITLE
Metrics being calculated? (il baseline)

### ISSUE THREAD

**Issue by YasMME** [facebookresearch/habitat-lab#610]
In the update method in metrics.py: https://github.com/facebookresearch/habitat-lab/blob/master/habitat_baselines/il/metrics.py, besides the mean of the metric, two other calculations are being saved. They look like some kind of weighting, but what exactly are they?

**Comment by mukulkhanna** [comment]
@YasMME In the `update` method, the following are being computed (in the same order) --

- Overall metric mean (of all the processed mini-batches)
- Exponential moving average -- a smoothed version of the metric to avoid drastic changes to the metric based on mini-batch statistics during training (sourced from the [original implementation](https://github.com/facebookresearch/EmbodiedQA))
- Current mini-batch mean
