### ISSUE TITLE
Unique seed not set for each simulator

### ISSUE THREAD

**Issue by Tushar-N** [facebookresearch/habitat-lab#611]
Habitat-Lab: v0.1.7 & master

## 🐛 Bug

Each environment should get a unique seed, but it looks like each process in the process group is provided the same seed in this code: https://github.com/facebookresearch/habitat-lab/blob/a7eb39fb3b420f9e6f528796f97457715bd79a09/habitat_baselines/rl/ppo/ppo_trainer.py#L217
```
# Multiply by the number of simulators to make sure they also get unique seeds
self.config.TASK_CONFIG.SEED += (
    torch.distributed.get_world_size()
    * self.config.NUM_ENVIRONMENTS
)
```

## Expected behavior
As far as I understand, `torch.distributed.get_world_size()` is a fixed number (the number of processes in the process group). Instead, shouldn't `local_rank` be used to modify the seed?
```
# Multiply by the number of simulators to make sure they also get unique seeds
self.config.TASK_CONFIG.SEED += (
    local_rank
    * self.config.NUM_ENVIRONMENTS
)
```

**Comment by dhruvbatra** [comment]
CC: @mathfac

**Comment by erikwijmans** [comment]
Yeah, that should be `torch.distributed.get_rank()`.  Made a PR
