### ISSUE TITLE
Resuming PPO training

### ISSUE THREAD

**Issue by yuyecreus** [facebookresearch/habitat-lab#638]
Hello everybody,

I was wondering if there is an implemented approach on resuming a PPO training from a saved checkpoint. Otherwise, if someone could give me an intuition on how to load a PPO checkpoint (as it is done for evaluation) only at the beginning of a training experiment it would be much appreciated.

Thank you very much!

**Comment by mathfac** [comment]
Hi @yuyecreus,

To preload the checkpoint you need to set next fields to True and checkpoint path:

https://github.com/facebookresearch/habitat-lab/blob/ce397c00195706f404019cfcbc4b1edceaae20a6/habitat_baselines/config/default.py#L148-L150

That fields to work for both PPO and DDPPO trainers.

Regarding resuming training there was recent functionality added here https://github.com/facebookresearch/habitat-lab/pull/615 that saves not only checkpoint, but also training schedule and other data needed to smooth training resume. https://github.com/facebookresearch/habitat-lab/blob/7964c9ee9fd9bda01ad8709981debb9f408646d6/habitat_baselines/rl/ddppo/ddp_utils.py#L155
