### ISSUE TITLE
Using habitat-sim simulator inside habitat-lab

### ISSUE THREAD

**Issue by gianscarpe** [facebookresearch/habitat-lab#645]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: master

Habitat-Sim: master

## ❓ Questions and Help

Hi everyone, I was wondering if it's possible to define an habitat-sim Simulator and use it as part of habitat-lab Env class. Is there any wrapper to adapt habitat-sim to habitat-lab? Many thanks! :)

**Comment by erikwijmans** [comment]
Habitat-lab uses habitat-sim in all nearly all cases (the only case that it doesn't is when using pyrobot to deploy in reality).
