### ISSUE TITLE
Expert Actions for Exploration

### ISSUE THREAD

**Issue by ugurbolat** [facebookresearch/habitat-lab#672]
Hi Habitat devs!

I was wondering if is there any dataset/environment (i.e., Replica, MP3D, etc.) that provides expert navigation actions for exploring the environment? I would like to experiment with building a semantic map, but it would be helpful if I can simplify the problem by disabling the action part for starters.

**Comment by dhruvbatra** [comment]
CC: @vincentcartillier

**Comment by vincentcartillier** [comment]
Hi @ugurbolat , this sounds very familiar. You should take a look at our Semantic MapNet project: 
- https://vincentcartillier.github.io/smnet.html
- https://github.com/vincentcartillier/Semantic-MapNet

In this project we build topdown semantic maps of an explored space (work done in MP3D and Replica). The exploration strategy here is assumed provided by an external policy or an oracle. In practice we've manually recorded those trajectories. And you can find those pre-recorded paths here: 
https://github.com/vincentcartillier/Semantic-MapNet/blob/main/data/paths.json

**Comment by ugurbolat** [comment]
Hi @vincentcartillier, 

Thanks for the leads. This is exactly what I needed. Let me dig into your repo.
