### ISSUE TITLE
About rearrangepick running

### ISSUE THREAD

**Issue by phj128** [facebookresearch/habitat-lab#673]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: vx.x.x or master?

master

Habitat-Sim: vx.x.x or master?

master

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest release versions of [Habitat-Lab](https://github.com/facebookresearch/habitat-lab/releases) and [Habitat-Sim](https://github.com/facebookresearch/habitat-sim/releases)? Your question may already be addressed in the latest versions. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Master branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-lab/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help

Is Rearrangepick in habitat_baselines/config/rearrange available to run? I have encountered a lot of bugs.

**Comment by ASzot** [comment]
Could you run `python example/example.py` and report any errors you are having there? Also note that this pull request fixes some issues in the Pick task training: https://github.com/facebookresearch/habitat-lab/pull/674. This pull request should be merged soon.
