### ISSUE TITLE
AttributeError: CONTENT_SCENES

### ISSUE THREAD

**Issue by jadkins99** [facebookresearch/habitat-lab#675]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.2.0

Habitat-Sim: v0.2.0

When I run examples/interactive_play.py I receive an attribute error. 

![Screenshot from 2021-07-07 21-28-59](https://user-images.githubusercontent.com/48653578/124848252-7a850f00-df6a-11eb-9409-421d70386317.png)

## Steps to Reproduce

1. python examples/interative_play.py --cfg configs/tasks/rearrangpick_replica_cad_example.yaml

**Comment by ASzot** [comment]
Hello, thanks for reporting this. Unfortunately, the interactive play script was accidentally included in the release and was not ready yet. The interactive play script is fixed in this pull request: https://github.com/facebookresearch/habitat-lab/pull/674. This pull request should be merged soon.
