### ISSUE TITLE
Crash when running examples/tutorials/nhp_python/Habitat_Interactive_Tasks.py

### ISSUE THREAD

**Issue by jadkins99** [facebookresearch/habitat-lab#678]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.2.0

Habitat-Sim: v0.2.0

Habitat is under active development, and we advise users to restrict themselves to stable releases of [Habitat-Lab](https://github.com/facebookresearch/habitat-lab/releases) and [Habitat-Sim](https://github.com/facebookresearch/habitat-sim/releases). The bug you are about to report may already be fixed in the latest version.

Master branch contains 'bleeding edge' code, but we do appreciate bug reports for it!

## 🐛 Bug
Get a segmentation fault (core dumped) error when trying to runthe Habitat_Interactive_Tasks.py tutorial code. 

## Steps to Reproduce

1.  python  examples/tutorials/nb_python/Habitat_Interactive_Tasks.py 

Please note that without a minimal working example to reproduce the bug, we may not be able to help you.

![Screenshot from 2021-07-08 14-42-03](https://user-images.githubusercontent.com/48653578/124974673-12323e00-dffb-11eb-9d1f-7057cc1794ea.png)

## Expected behavior
Was expecting to run the Interactive Task Tutorial.

**Comment by erikwijmans** [comment]
You need to download the required scene, run
```bash
python -m habitat_sim.utils.datasets_download --uids coda_scene --data-path ./data
```
to download that.

**Comment by jadkins99** [comment]
Okay, thank you! After downloading the scene and running again, there is a IndexError: list out of range error. What is the cause of this?
![Screenshot from 2021-07-08 15-46-02](https://user-images.githubusercontent.com/48653578/124981615-c3d56d00-e003-11eb-91a6-9a4d07f0c1d1.png)

**Comment by erikwijmans** [comment]
Likely missing some additional assets, 
```shell
python -m habitat_sim.utils.datasets_download --uids ci_test_assets --data-path ./data
```
should get all the needed ones.

**Comment by jadkins99** [comment]
Great! Thank you!
