### ISSUE TITLE
Question regarding the EpisodicGPSSensor's position data

### ISSUE THREAD

**Issue by zxwang96** [facebookresearch/habitat-lab#710]
Hi,

I find the following code reverses the order of x and z in the simulation environment. I wonder why you do this? Thank you!
https://github.com/facebookresearch/habitat-lab/blob/9220a301c3b168f845150a3d2f20df8fc21f3842/habitat/tasks/nav/nav.py#L456

**Comment by erikwijmans** [comment]
This is just transforming the 3D coordinate system to the 2D coordinate system.  We use +x is forward and +y is right in 2D.
