### ISSUE TITLE
Bug when running trainer.eval() in run.py 

### ISSUE THREAD

**Issue by quintus0505** [facebookresearch/habitat-lab#717]
I am using stable branch in habitat-lab. After I finished training my agent and trying to evaluate by using ```trainer.eval()``` in ```run.py```, I there was an err. I removed the original habitat conda-env and rebuilt it following the instructions in readme but still got the same problem :```BrokenPipeError: [Errno 32] Broken pipe``` in ```imageio-ffmpeg```

I managed to solve it so I didn't save the output from terminal. It seems that conda's ffmpeg in anaconda3/envs/habitat/bin/ffmpeg does not bring h264 codec (especially, it lacks encoder), so I run this command and solve the problem suggested  in https://superuser.com/questions/1420351/how-to-use-libx264-ffmpeg-in-conda-environment
```
conda install x264=='1!152.20180717' ffmpeg=4.0.2 -c conda-forge
```

Hope this can help!

**Comment by mathfac** [comment]
Thank you for the reporting the solution, @quintus0505. Will check if that replicates on our CI setup.
