### ISSUE TITLE
I can't run the quick start example

### ISSUE THREAD

**Issue by JiayunjieJYJ** [facebookresearch/habitat-lab#718]
## ❓ Questions and Help
I can run the QuickStart example.
There are so many dataset url for **gibson** dataset, as shown in the Readme.md: https://github.com/facebookresearch/habitat-lab#Gibson  

I can't download the right **gibson** dataset so I can't run the quickstart, could you please tell my the exact download url of the  **gibson** dataset?  

![image](https://user-images.githubusercontent.com/44229958/132881335-6c584ca9-a9b5-474f-ae31-b76f2259f9e0.png)

I need the .glb file like this:  
![image](https://user-images.githubusercontent.com/44229958/132881407-48d90969-1e58-42ce-8b45-4e0df091c02f.png)

Thanks a lot !!!

**Comment by JiayunjieJYJ** [comment]
I can't run the quick start example

**Comment by JiayunjieJYJ** [comment]
Could you please tell me the exact download url of the gibson dataset which is 1.5GB and contains the '.glb' files?

**Comment by dhruvbatra** [comment]
https://github.com/facebookresearch/habitat-sim/blob/master/DATASETS.md
