### ISSUE TITLE
Can hatbitat support importing URDF models

### ISSUE THREAD

**Issue by zsl13734413436** [facebookresearch/habitat-lab#722]
Can hatbitat support importing URDF models

**Comment by aclegg3** [comment]
Hey @zsl13734413436, Habitat does support URDF. See the tests starting [here](https://github.com/facebookresearch/habitat-sim/blob/e51d955eae7aea0ed6406e54d2cf071913c9e2a1/tests/test_physics.py#L638) for example code.
