### ISSUE TITLE
DD-PPO RL Baseline - Visual Input Size Not 256x256 

### ISSUE THREAD

**Issue by RobertHalwass** [facebookresearch/habitat-lab#727]
I was wondering what exactly happens, when the input size of RGB and/or Depth Sensor is not equal to 256x256. I tried it with 400x300 and the program didn’t raise any errors and training seemed to work. What kind of transform is applied? I wasn’t able to find a direct answer by looking through the code. Is it a Center Crop (like CenterCropper from the Batch Obs Transforms) or does it stretch the image?

**Comment by rpartsey** [comment]
Closing the issue because it has not had recent activity. Feel free to re-open the issue, if you still have questions.
