### ISSUE TITLE
opt/conda/bin/conda not found when building Dockerfile

### ISSUE THREAD

**Issue by NickLucche** [facebookresearch/habitat-lab#728]
## 🚀 Feature
As title, I run into this error when building from Dockerfile; apparently it's caused by curl missing the "follow redirects" flag and thus not installing conda. Solution is to append the -L flag to curl as described in this answer https://stackoverflow.com/a/63367463 to a related problem.

## Pitch
`curl -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh`->``curl -L -o ~/miniconda.sh -O  https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh``

**Comment by dhruvbatra** [comment]
Thanks for pointing this out. Would you mind sending us a PR?
