### ISSUE TITLE
Missing hab_fetch.urdf file?

### ISSUE THREAD

**Issue by emigmo** [facebookresearch/habitat-lab#749]
## Habitat-Lab and Habitat-Sim versions
Both Habitat-Lab and Habitat-Sim are master.

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help
The robot description file of fetch within habitation-sim is missing? 
In the rearrange task, the hab_fetch.urdf file is defined in the rearrangepick_replica_cad.yaml 
I can not find it.

**Comment by aclegg3** [comment]
Hey @emigmo,
You'll need to download the rearrange asset files. You can do so automatically with the [datasets_downloader](https://github.com/facebookresearch/habitat-sim/blob/b45d800b0b99ae52486732f8676f6c27e42cfc8f/habitat_sim/utils/datasets_download.py#L194) from habitat-sim.

For example:
```
#with installed module instead of source:`python -m habitat_sim.utils.datasets_download`
python path/to/habitat_sim/utils/datasets_download.py --uids rearrange_task_assets --data-path path/to/habitat-lab/data/     
```
