### ISSUE TITLE
Generalization of the tutorial code

### ISSUE THREAD

**Issue by yhymason** [facebookresearch/habitat-lab#757]
Hi there, I have been reading through the Habitat 2020 tutorials. I tried the tutorial's code and ran
```
if __name__ == "__main__":
    trainer_init = baseline_registry.get_trainer(config.TRAINER_NAME)
    trainer = trainer_init(config)
    trainer.train()
```
it only seemed to train one iteration/episode according to `ppo_trainer.py`, how should I formulate the code to train on all scenes and all episodes for mp3d datasets? Are there any fully implemented examples I can refer to?

**Comment by erikwijmans** [comment]
Answered in https://github.com/facebookresearch/habitat-lab/issues/735#issuecomment-957798783
