### ISSUE TITLE
Confusion about simulation device

### ISSUE THREAD

**Issue by moyutianque** [facebookresearch/habitat-lab#775]
Hi thanks for the great project. 

Which part does the simulator use the GPU device, get_observation, step, or other functions?
I set 16 envs in VectorEnv and stepped the agent in a navigation task with ground truth action sequences. But I could not observe the GPU was actively computing. 

I do not use the RGB and Depth sensor but only use the topdown map and detect collision in the simulator. 

Is the simulation a CPU-intensive task? If this is abnormal, how could I check what device is being used in a certain simulation stage?

Thanks

**Comment by erikwijmans** [comment]
Only rendering uses the GPU, so if you aren't rendering out Depth/RGB/Semantics the GPU won't be used. Computing the top-down map can be pretty CPU intensive -- the cost to compute it grows linearly with the number of pixels in it.

**Comment by moyutianque** [comment]
Thanks!
