### ISSUE TITLE
Tasks other than PointNav

### ISSUE THREAD

**Issue by serenamou** [facebookresearch/habitat-lab#8]
Will alternate tasks (Object Goal, Area Goal etc) be released? If so, is there an approximate timeline?

**Comment by abhiskk** [comment]
Releasing for other tasks is definitely on our Roadmap but we don't have an approximate timeline for it yet. We do welcome any external contributions on this, if you are willing to take this up I can work closely with you for implementing the alternate tasks.

Thanks.

**Comment by rpartsey** [comment]
The habitat platform now supports a wide range of tasks (PointGoal, ObjectGoal, Rearrangement).
New tasks can be defined by extending the habitat code.

Closing the issue because it has not had recent activity.
