### ISSUE TITLE
How to ignore the following warning?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/habitat-lab#814]
warning come from the code [ManagedPhysicsObjectBase.h:324](https://github.com/facebookresearch/habitat-sim/blob/91f322cf72ec225742e54095728680aeed6e4ac8/src/esp/physics/objectWrappers/ManagedPhysicsObjectBase.h#L320)
```
W0221 16:34:14.326818 26834 ManagedPhysicsObjectBase.h:324] This object no longer exists. Please delete any variable references.
```
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.2.1

Habitat-Sim: v0.2.1

![image](https://user-images.githubusercontent.com/34536352/154963611-a28d007b-94a6-4718-93ee-d42807388c8d.png)

**Comment by aclegg3** [comment]
Hey, @yyf17,

You can configure logging levels as described in [this doc page](https://aihabitat.org/docs/habitat-sim/logging.html). 

This warning is originating from trying to access objects wrappers for objects which have already been deleted. I suggest you address the underlying source issues to avoid unexpected behavior.
