### ISSUE TITLE
Problem with loading semantic from MP3D dataset

### ISSUE THREAD

**Issue by alstar8** [facebookresearch/habitat-lab#835]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: master
Habitat-Sim: master

## 🐛 Bug

When I load the MP3D dataset, the semantic seems rotated and get a view outside from building

## Steps to Reproduce

Notebook to reproduce this issue
[habitat_example.zip](https://github.com/facebookresearch/habitat-lab/files/8335824/habitat_example.zip)

![image](https://user-images.githubusercontent.com/37709904/159776486-7037bc9a-ea2c-4f5b-b366-257c8c3e28e4.png)

## Additional context

With stable version of Habitat I have no such an issue

**Comment by dhruvbatra** [comment]
CC: @jturner65. Looks like a config issue.

**Comment by alstar8** [comment]
@dhruvbatra @jturner65 Still got that problem, any advice what to change in config to fix that?

**Comment by Jthon-lab** [comment]
I've got the same problem, do you know how to change the config? Thank you @alstar8.

**Comment by aclegg3** [comment]
https://github.com/facebookresearch/habitat-sim/issues/1808

**Comment by MlLearnerAkash** [comment]
I also have the same issue.
Did anybody solve that?
