### ISSUE TITLE
How to change the reward function

### ISSUE THREAD

**Issue by wangyingfan-day** [facebookresearch/habitat-lab#852]
If i need to change the reward function, where can i find it in the habitat-lab folder

**Comment by dhruvbatra** [comment]
Please see: https://colab.research.google.com/github/facebookresearch/habitat-lab/blob/master/examples/tutorials/colabs/Habitat_Lab.ipynb (RLEnv)

**Comment by dhruvbatra** [comment]
Also: https://aihabitat.org/tutorial/2020/

**Comment by wangyingfan-day** [comment]
thanks
