### ISSUE TITLE
How to get the end point of the episode and the shortest path showing on the top down map of HM3D data?

### ISSUE THREAD

**Issue by yahsieh37** [facebookresearch/habitat-lab#914]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: v0.2.2 (stable)

Habitat-Sim: v0.2.2 (stable)

Habitat is under active development, and we advise users to restrict themselves to stable releases. Are you using the latest release versions of [Habitat-Lab](https://github.com/facebookresearch/habitat-lab/releases) and [Habitat-Sim](https://github.com/facebookresearch/habitat-sim/releases)? Your question may already be addressed in the latest versions. We may also not be able to help with problems in earlier versions because they sometimes lack the more verbose logging needed for debugging.

Master branch contains 'bleeding edge' code and should be used at your own risk.

## Docs and Tutorials
Did you read the docs? https://aihabitat.org/docs/habitat-lab/

Did you check out the tutorials? https://aihabitat.org/tutorial/2020/

Perhaps your question is answered there. If not, carry on!

## ❓ Questions and Help
Hello,
I'm trying to visualize the trained PPO PointNav agent on the HM3D dataset. I ran the `habitat_baseline/run.py` with `--run-type eval` and `VIDEO_OPTION: ["disk", "tensorboard"]` in the config file. The generated video did show the top down map along with the start point of the episode and trajectory of the agent. However, I was not able to have the end point of the episode and the shortest path also showing on the top down map (as shown below). Any suggestions would be helpful, thanks!

![image](https://user-images.githubusercontent.com/51134954/181123145-c929f4b9-432b-447b-85ab-a3377e247df4.png)

**Comment by dhruvbatra** [comment]
Please read the "Habitat-Sim for Navigation" tutorial section on Navmesh. https://aihabitat.org/tutorial/2020/
