### ISSUE TITLE
Missing :- handcrafted-agent-example.ipynb 

### ISSUE THREAD

**Issue by kowshikthopalli** [facebookresearch/habitat-lab#95]
Hi,
Thanks for this wonderful repo.
In slam based agents folder in habitat baselines , it has been stated that there is a notebook titled 'handcrafted-agent-example.ipynb ' .
I could not find the same. Can you please point to it?

**Comment by mathfac** [comment]
Maybe @ducha-aiki can share it with you.

**Comment by ducha-aiki** [comment]
Hi,
It was lost when adopting to version changes, but I can recreate and upload it next week.

**Comment by Tiga002** [comment]
@ducha-aiki  
Hi ! Thanks for your great effort ! 
However, I still couldn't find the handcrafted-agent-example.ipynb in the master branch. 
Would you like to upload it again ?

**Comment by keita-rgit** [comment]
Hi,
Thank you for making excellent work.
I want to try the SLAM in Habitat too, so please upload "../handcrafted-agent-example.ipynb".
I tried it by following the instructions below, but I didn't know how to run the slambased.
[https://github.com/facebookresearch/habitat-api/tree/master/habitat_baselines/slambased](url)

**Comment by ducha-aiki** [comment]
Hi,

I will upload it as soon as be able to install habitat itself :)

https://github.com/facebookresearch/habitat-sim/issues/491

**Comment by manikamakam** [comment]
Hello, 

I cannot find the "handcrafted-agent-example.ipynb". Can someone point me towards it or any other resource which explains how to use their 'slambased' baseline? Thanks in advance.

**Comment by morpheus1820** [comment]
Hi! Has the example notebook "handcrafted-agent-example.ipynb" been made available yet?

**Comment by dhruvbatra** [comment]
I think it's safe to assume that at this point that we no longer support any SLAM-based agent with the current version of the code.
