### ISSUE TITLE
TopDownMap plotting goal position

### ISSUE THREAD

**Issue by shuhangchen** [facebookresearch/habitat-lab#953]
## Habitat-Lab and Habitat-Sim versions
Habitat-Lab: main

Habitat-Sim: v0.2.2 

Master branch contains 'bleeding edge' code, but we do appreciate bug reports for it!

## 🐛 Bug

TopDownMap does not plot goal position in navigation task when the episode of environment contains attribute "goals"

## Steps to Reproduce

1. python examples/shortest_path_follower_example.py

I believe the bug is a typo in https://github.com/facebookresearch/habitat-lab/blob/e2cb80843f6ddf24ffd3964976a5136963c03568/habitat/tasks/nav/nav.py#L875 
```
    if hasattr(episode, "goal"):
            # draw source and target parts last to avoid overlap
            self._draw_goals_view_points(episode)
            self._draw_goals_aabb(episode)
            self._draw_goals_positions(episode)
            self._draw_shortest_path(episode, agent_position)
```
where `goal` should be `goals`.  

After fixing this typo, the topdownmap works on my local machine.

**Comment by rpartsey** [comment]
Fixed in https://github.com/facebookresearch/habitat-lab/pull/1032.
