### ISSUE TITLE
not able to completely dwnld H-lab

### ISSUE THREAD

**Issue by parzaech** [facebookresearch/habitat-lab#993]
after completely downloading habitat sim and cloning 
![Screenshot from 2022-11-08 17-30-57](https://user-images.githubusercontent.com/58459090/200558800-2a54ee30-699b-49bc-8c2f-98a992b85774.png)
this error is coming :
![Screenshot from 2022-11-08 17-31-57](https://user-images.githubusercontent.com/58459090/200558923-2cc8d93b-862c-45d5-abcd-f624d65640ad.png)
Please help.
Thanks.

**Comment by alper111** [comment]
Try `pip install -e .`

**Comment by parzaech** [comment]
yup thanks, this worked.
